// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-OATUutSrcL6gEubGJfaJjPS7y10g4k',
    appId: '1:694012428731:web:2bac0942e9f909b38e449e',
    messagingSenderId: '694012428731',
    projectId: 'closey-ai-coach',
    authDomain: 'closey-ai-coach.firebaseapp.com',
    storageBucket: 'closey-ai-coach.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BYAlUbuMZ87xEKFYi8iD8ZSZ6SakgBQ',
    appId: '1:694012428731:android:812933f7197cc4aa8e449e',
    messagingSenderId: '694012428731',
    projectId: 'closey-ai-coach',
    storageBucket: 'closey-ai-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO3IYhURrLwEwOKOsZaBKGKfm1dysS44Y',
    appId: '1:694012428731:ios:8cd9219b94ed4a098e449e',
    messagingSenderId: '694012428731',
    projectId: 'closey-ai-coach',
    storageBucket: 'closey-ai-coach.firebasestorage.app',
    iosBundleId: 'com.closey.closey',
  );
}
